name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-60-135-196.eu-north-1.compute.amazonaws.com << 'EOF'
            set -e
            cd /home/ubuntu/Fastapi
            git fetch origin main
            git reset --hard origin/main

            sudo docker build -t fastapi-app .
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true
            sudo docker run -d -p 80:80 --restart unless-stopped --name fastapi-app fastapi-app
          EOF
